### ISSUE TITLE
Inconsistent attendance percentage 

### ISSUE THREAD

**Issue by Shreyaahx** [therealsujitk/android-vtop-chennai#100]
## Bug Report

**Current Behavior**
The overall attendance percentage displayed is wrong because the attendance of each course varies from what's given in VTOP.

**Steps to Reproduce**

**Expected Behavior**
There is an inconsistency with the attendance percentage displayed for each course with what's given on vtop. Tus affects my overall percentage display as well

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment]
Can you show some screenshots? The attendance percentage is calculated manually on the app because sometimes VTOP makes mistakes. In the case of attendance I've just dropped everything after the decimal instead of rounding off since it seemed safer than showing a higher attendance that what is on VTOP.

**Comment by Shreyaahx** [comment]
My attendances are 93,97,90,97,93,95,89. But the attendance percentage displayed in app is 92%

**Comment by therealsujitk** [comment]
@Shreyaahx what are the respective individual attendance percentages according to the app?

**Comment by Shreyaahx** [comment]
@therealsujitk 92,96,90,96,92,94,88 in the same order of subjects I've given in my previous comment

**Comment by therealsujitk** [comment]
The fix will be shipped with the next version. (>**v4.3.1**)
