### ISSUE TITLE
Data Syncing Fails with Error 201 - No value for semesters

### ISSUE THREAD

**Issue by AishikTokdar** [therealsujitk/android-vtop-chennai#109]
## Bug Report

**Current Behavior**
When syncing data, after filling the captcha, error 201 appears, which results in the captcha reappearing. This behavior keeps looping.

**Steps to Reproduce**

1. Go to 'Profile'
2. Click on 'Sync Data'
3. Fill Captcha
4. "Error 201. No value for semesters" appears.
5. Captcha Reappears.

**Expected Behavior**
Expected to see a successful login and sync of data.

**Screenshots**

**Environment**

- Android version: 
Android version: 13

**Comment by AishikTokdar** [comment]
@therealsujitk The error has reappeared today!

**Comment by OneRandom1509** [comment]
Seems like a user-agent issue again, I have the solution and I'll make a PR right now

**Comment by therealsujitk** [comment]
I had a hunch, but I thought I might've been overthinking it. It's possible VIT might be purposely blocking user agents we use so that people stop using this app and use their official one instead. In doing so they're also affecting normal traffic, now I can't even use VTOP from my mac.

<img width="1157" alt="Screenshot 2024-03-22 at 13 46 34" src="https://github.com/therealsujitk/android-vtop-chennai/assets/60378235/11e5718b-3e2e-44a3-8283-62fd74c50c5e">

<hr>

We can't keep changing this and releasing an update every two days, have to think of a better solution.

**Comment by AishikTokdar** [comment]
@therealsujitk Can adding a bunch of user agents, where the app selects a random one every time, help?

**Comment by therealsujitk** [comment]
@AishikTokdar it is a solution, but I don't like it very much. Let's see if we can think of something else for now, otherwise we'll have to go with that only.

**Comment by AishikTokdar** [comment]
@therealsujitk We just need to ensure that a lot of user agents are put, since thousands of people use the app daily,

**Comment by therealsujitk** [comment]
Will release this later tonight, I'm planning to include some minor crash fixes before releasing.
