### ISSUE TITLE
Sync data fails while downloading attendance

### ISSUE THREAD

**Issue by praneeth55** [therealsujitk/android-vtop-chennai#44]
![IMG-20220704-WA0003](https://user-images.githubusercontent.com/66474087/177196453-ca283fc2-e649-478c-b70d-98af9c4061f8.jpg)
App crashes while loading attendance when I sync
![Screenshot_20220704-223050_VIT Student](https://user-images.githubusercontent.com/66474087/177195943-22ebfdee-36f3-4753-808b-adc644a3826d.jpg)

**Comment by therealsujitk** [comment]
@praneeth55 can you try logging out of VIT Student and logging back in? It should temporarily resolve the issue.

**Comment by therealsujitk** [comment]
The table `assignments` is dropped instead of `attendance` in [`AttendanceDao.java`](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/interfaces/AttendanceDao.java#L17), this should be fixed.

Some students also face this issue when they haven't completed the fee payment yet.

**Comment by therealsujitk** [comment]
Fixed in commit 004573a80a21db8dc64bcd05c0428c72953a6ff8.
