### ISSUE TITLE
Material theme gets reset when app is terminated by system

### ISSUE THREAD

**Issue by logicalNil** [therealsujitk/android-vtop-chennai#65]
## App colour get  change after process death .

<img src="https://user-images.githubusercontent.com/80938367/204106101-af3f7315-5952-440e-ac24-7321839879b2.jpg" height="500px">

**Comment by therealsujitk** [comment]
What do you mean by process death?

**Comment by nilay-coder** [comment]
`Process Death :-` _System-initiated process death means the process is killed by the Android operating system. It could be due to resource constraints (not enough memory) or simply configuration changes (screen rotation)._

**When I minimise app for short interval of time then after I reopen the app then I get this screen**

**Comment by therealsujitk** [comment]
This should be fixed in https://github.com/therealsujitk/android-vtop-chennai/commit/37ff267453d7227f0851d1cc2c91832ae299259a, will be visible in the next release (>**v4.2.2**).
